import { TenantConfig } from './types';

export const mentanailConfig: TenantConfig = {
  id: 'mentanail',
  slug: 'mentanail',
  businessId: 'f88f93c9-563b-42e1-9624-3a8817cab842',
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL_MENTANAIL ?? '',
  supabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY_MENTANAIL ?? '',
  labels: {
    booking: 'תור',
    bookings: 'תורים',
    makeBooking: 'קביעת תור',
    calendar: 'יומן תורים',
    services: 'השירותים שלנו',
    service: 'שירות',
    customer: 'לקוחה',
    customers: 'לקוחות',
    register: 'הרשמה כלקוחה',
    businessOwner: 'כניסת בעלת העסק',
    confirmCancel: 'בטוחה שלבטל את התור?',
    myBookings: 'התורים שלי',
    changeDate: 'שינוי מועד',
    hello: 'שלום',
    rescheduleMsg: (svc, date, time) =>
      `היי, אני רוצה לשנות מועד של התור ל${svc} ב-${date} בשעה ${time}`,
    cancelMsg: (svc, date, time) =>
      `היי, אני צריכה לבטל את התור ל${svc} ב-${date} בשעה ${time}`,
    bookingSettings: 'הגדרות קביעת תורים',
    advanceBookingLabel: 'כמה זמן קדימה ניתן לקבוע תור?',
    advanceBookingHint: 'לקוחות יוכלו לקבוע תורים רק בטווח הזמן שנבחר',
    maxBookingsLabel: 'כמה תורים לקוחה יכולה לקבוע קדימה?',
    maxBookingsHint: 'מונע מלקוחה לתפוס יותר מדי תורים בו-זמנית',
    cancelBookingLabel: 'ביטול תור',
    cancelFromSite: 'לקוחות יוכלו לבטל תורים ישירות מהאתר',
    cancelViaWhatsapp: 'לקוחות יצטרכו ליצור קשר בוואטסאפ לביטול תור',
    servicePlaceholder: "מניקור ג'ל",
    clientSeesBit: 'הלקוחה תראה כפתור ביט עם המספר שלך והסכום 💳',
    clientSeesPaybox: 'הלקוחה תראה כפתור פייבוקס עם המספר שלך והסכום 💳',
    logoHint: 'העלי לוגו לתצוגה מושלמת. גם תמונה שלך יכולה לעבוד. אם אין, תשאירי ריק 😊',
  },
  features: {
    autoApprove: false,
    groupSessions: false,
    customerCategories: false,
    showPrice: true,
    showDuration: true,
  },
  defaultColors: {
    primary: '#14b898',
    secondary: '#f0fdf9',
    background: '#fafffe',
  },
  defaultPassword: 'menta2024',
  storagePrefix: 'mentanail',
};
