import { TenantConfig } from './types';

export const studio180Config: TenantConfig = {
  id: 'studio180',
  slug: '180studio',
  category: 'fitness',
  businessId: 'e27f7a45-251a-4b47-ba21-a395533aaca0',
  supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL_MENTANAIL ?? '',
  supabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY_MENTANAIL ?? '',
  labels: {
    booking: 'אימון',
    bookings: 'אימונים',
    makeBooking: 'קביעת אימון',
    calendar: 'יומן אימונים',
    services: 'סוגי האימונים',
    service: 'אימון',
    customer: 'לקוח',
    customers: 'לקוחות',
    register: 'הרשמה כלקוח',
    businessOwner: 'כניסת בעל העסק',
    confirmCancel: 'בטוח שלבטל את האימון?',
    myBookings: 'האימונים שלי',
    changeDate: 'שינוי מועד',
    hello: 'שלום',
    rescheduleMsg: (svc, date, time) =>
      `היי, אני רוצה לשנות מועד של האימון ${svc} ב-${date} בשעה ${time}`,
    cancelMsg: (svc, date, time) =>
      `היי, אני צריך לבטל את האימון ${svc} ב-${date} בשעה ${time}`,
    bookingSettings: 'הגדרות קביעת אימונים',
    advanceBookingLabel: 'כמה זמן קדימה ניתן לקבוע אימון?',
    advanceBookingHint: 'לקוחות יוכלו לקבוע אימונים רק בטווח הזמן שנבחר',
    maxBookingsLabel: 'כמה אימונים לקוח יכול לקבוע קדימה?',
    maxBookingsHint: 'מונע מלקוח לתפוס יותר מדי אימונים בו-זמנית',
    cancelBookingLabel: 'ביטול אימון',
    cancelFromSite: 'לקוחות יוכלו לבטל אימונים ישירות מהאתר',
    cancelViaWhatsapp: 'לקוחות יצטרכו ליצור קשר בוואטסאפ לביטול אימון',
    servicePlaceholder: 'אימון אישי',
    clientSeesBit: 'הלקוח יראה כפתור ביט עם המספר שלך והסכום 💳',
    clientSeesPaybox: 'הלקוח יראה כפתור פייבוקס עם המספר שלך והסכום 💳',
    logoHint: 'העלה לוגו לתצוגה מושלמת. גם תמונה שלך יכולה לעבוד. אם אין, תשאיר ריק 😊',
    customerApproved: 'מאושר! 🏋️',
    customerPending: 'ממתין לאישור',
    pendingTab: 'ממתינים לאישור',
    noPendingCustomers: 'אין לקוחות ממתינים! 🎉',
    customersListEmpty: 'עוד רגע מגיעים! 🏋️ רשימת הלקוחות שלך ריקה',
    customerApprovedToast: 'הלקוח אושר! 🎉',
    sendWhatsappApproval: 'שלח הודעה בוואטסאפ',
    customerApprovalMsg: (name, businessName, url) =>
      `היי ${name}! אושרת כלקוח ב-${businessName} 🏋️ אפשר לקבוע אימון: ${url}`,
  },
  features: {
    autoApprove: true,
    groupSessions: true,
    customerCategories: true,
    showPrice: false,
    showDuration: true,
  },
  defaultColors: {
    primary: '#00BCD4',
    secondary: '#E0F7FA',
    background: '#F5FEFF',
  },
  defaultPassword: '180admin',
  storagePrefix: 'studio180',
};
